-- 코드를 입력하세요
SELECT HOUR(DATETIME) AS 'HOUR', COUNT(DATETIME) AS 'COUNT'
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19 -- 09:00~19:59 조건 설정
GROUP BY HOUR
ORDER BY HOUR

# 2
# SELECT HOUR(DATETIME) AS 'HOUR', COUNT(HOUR(DATETIME)) AS 'COUNT'
# FROM ANIMAL_OUTS
# GROUP BY HOUR
# HAVING HOUR BETWEEN 9 AND 19 -- 09:00~19:59 조건 설정
# ORDER BY HOUR