SELECT DISTINCT C.car_id
FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    ON C.car_id = H.car_id
WHERE CAR_TYPE = '세단'
    AND START_DATE between '2022-10-01' and '2022-10-31' 
ORDER BY C.car_id DESC